# Generated by Django 3.1.6 on 2021-02-12 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vscode_info', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vscodeinfo',
            name='last_name',
        ),
    ]
