# Generated by Django 3.1.7 on 2021-03-24 15:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                ('text', models.TextField(blank=True)),
                ('path', models.TextField(blank=True)),
                ('bandit', models.TextField(blank=True)),
                ('banditIssues', models.TextField(blank=True)),
                ('loc', models.IntegerField(blank=True)),
                ('lloc', models.IntegerField(blank=True)),
                ('sloc', models.IntegerField(blank=True)),
                ('comments', models.IntegerField(blank=True)),
                ('multi', models.IntegerField(blank=True)),
                ('blank', models.IntegerField(blank=True)),
                ('singleComments', models.IntegerField(blank=True)),
                ('vulture', models.TextField(blank=True)),
                ('mccabe', models.TextField(blank=True)),
                ('pylint', models.TextField(blank=True)),
                ('dodgy', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
